"""Public client and lender portal — token-based access for buyers/sellers/lenders.

No authentication required for portal views. The token in the URL acts as the credential.
Tokens are generated by the broker and expire after 30 days.
"""

import logging
import secrets
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, field_validator
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.database import get_db
from app.middleware.auth import get_current_user
from app.models.document import Document
from app.models.portal_token import PortalToken
from app.models.transaction import Transaction
from app.models.user import User

router = APIRouter(tags=["portal"])
logger = logging.getLogger(__name__)


# ── Request schemas ──────────────────────────────────────────────────────────

class LenderTokenRequest(BaseModel):
    lender_name: str
    lender_email: str | None = None

    @field_validator("lender_name")
    @classmethod
    def lender_name_length(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Lender name is required")
        if len(v) > 200:
            raise ValueError("Lender name must be at most 200 characters")
        return v.strip()

    @field_validator("lender_email")
    @classmethod
    def lender_email_length(cls, v: str | None) -> str | None:
        if v is not None and len(v) > 300:
            raise ValueError("Lender email must be at most 300 characters")
        return v


class LenderDocUpload(BaseModel):
    name: str
    status: str = "pending"

    @field_validator("name")
    @classmethod
    def name_length(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Document name is required")
        if len(v) > 500:
            raise ValueError("Document name must be at most 500 characters")
        return v.strip()


@router.post("/transactions/{transaction_id}/portal-token", status_code=status.HTTP_201_CREATED)
async def create_portal_token(
    transaction_id: int,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Generate a magic link token for client portal access to a transaction.

    Returns the token (30-day validity). The frontend constructs the full URL.
    """
    result = await db.execute(
        select(Transaction).where(
            Transaction.id == transaction_id,
            Transaction.user_id == current_user.id,
        )
    )
    txn = result.scalar_one_or_none()
    if txn is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Transaction not found")

    token_str = secrets.token_urlsafe(48)
    expires_at = datetime.now(timezone.utc) + timedelta(days=30)

    portal_token = PortalToken(
        token=token_str,
        transaction_id=transaction_id,
        token_type="client",
        expires_at=expires_at,
    )
    db.add(portal_token)
    await db.flush()

    return {
        "token": token_str,
        "expires_at": expires_at.isoformat(),
        "transaction_id": transaction_id,
    }


@router.get("/portal/{token}")
async def get_portal_view(
    token: str,
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Public endpoint — return transaction status for a valid portal token.

    No authentication required. The token itself is the credential.
    Returns a curated view: address, status, parties, deadlines, key events.
    """
    now = datetime.now(timezone.utc)

    result = await db.execute(
        select(PortalToken)
        .where(PortalToken.token == token, PortalToken.expires_at > now)
        .options(
            selectinload(PortalToken.transaction).selectinload(Transaction.parties),
            selectinload(PortalToken.transaction).selectinload(Transaction.deadlines),
            selectinload(PortalToken.transaction).selectinload(Transaction.events),
        )
    )
    portal_token = result.scalar_one_or_none()
    if portal_token is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Portal link is invalid or has expired.",
        )

    txn = portal_token.transaction

    # Return curated view (no sensitive broker data)
    deadlines = [
        {
            "name": d.name,
            "due_date": d.due_date.isoformat(),
            "status": d.status,
        }
        for d in sorted(txn.deadlines, key=lambda x: x.due_date)
    ]

    # Only show non-dismissed client-facing events
    events = [
        {
            "event_type": e.event_type,
            "description": e.description,
            "created_at": e.created_at.isoformat(),
        }
        for e in sorted(txn.events, key=lambda x: x.created_at, reverse=True)
        if not e.dismissed
    ][:10]

    parties = [
        {
            "role": p.role,
            "full_name": p.full_name,
        }
        for p in txn.parties
    ]

    return {
        "address": txn.address,
        "property_type": txn.property_type,
        "status": txn.status,
        "purchase_price": txn.purchase_price,
        "closing_date": txn.closing_date.isoformat() if txn.closing_date else None,
        "parties": parties,
        "deadlines": deadlines,
        "events": events,
    }


# ── Lender portal endpoints ─────────────────────────────────────────────────


@router.post("/portal/lender-token/{transaction_id}", status_code=status.HTTP_201_CREATED)
async def create_lender_token(
    transaction_id: int,
    body: LenderTokenRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Generate a magic link token for lender portal access to a transaction.

    Returns the token (30-day validity). The frontend constructs the full URL.
    """
    result = await db.execute(
        select(Transaction).where(
            Transaction.id == transaction_id,
            Transaction.user_id == current_user.id,
        )
    )
    txn = result.scalar_one_or_none()
    if txn is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Transaction not found")

    token_str = secrets.token_urlsafe(48)
    expires_at = datetime.now(timezone.utc) + timedelta(days=30)

    portal_token = PortalToken(
        token=token_str,
        transaction_id=transaction_id,
        token_type="lender",
        lender_name=body.lender_name,
        lender_email=body.lender_email,
        expires_at=expires_at,
    )
    db.add(portal_token)
    await db.flush()

    return {
        "token": token_str,
        "expires_at": expires_at.isoformat(),
        "transaction_id": transaction_id,
        "lender_name": body.lender_name,
        "lender_email": body.lender_email,
    }


@router.get("/portal/lender/{token}")
async def get_lender_portal_view(
    token: str,
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Public endpoint — return lender portal data for a valid lender token.

    No authentication required. The token itself is the credential.
    Returns transaction summary + document list for uploading.
    """
    now = datetime.now(timezone.utc)

    result = await db.execute(
        select(PortalToken)
        .where(
            PortalToken.token == token,
            PortalToken.token_type == "lender",
            PortalToken.expires_at > now,
        )
        .options(
            selectinload(PortalToken.transaction).selectinload(Transaction.documents),
        )
    )
    portal_token = result.scalar_one_or_none()
    if portal_token is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Lender portal link is invalid or has expired.",
        )

    txn = portal_token.transaction

    # Filter documents relevant to lender
    uploaded_docs = [
        {
            "id": doc.id,
            "name": doc.name,
            "status": doc.status,
            "uploaded_at": doc.collected_at.isoformat() if doc.collected_at else doc.created_at.isoformat(),
        }
        for doc in txn.documents
    ]

    return {
        "transaction": {
            "id": txn.id,
            "address": txn.address,
            "status": txn.status,
            "closing_date": txn.closing_date.isoformat() if txn.closing_date else None,
        },
        "lender_name": portal_token.lender_name,
        "required_docs": [
            "Commitment Letter",
            "Clear to Close",
            "Final Loan Approval",
            "Closing Disclosure",
        ],
        "uploaded_docs": uploaded_docs,
    }


@router.post("/portal/lender/{token}/upload", status_code=status.HTTP_201_CREATED)
async def lender_upload_document(
    token: str,
    body: LenderDocUpload,
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Public endpoint — allow lender to submit a document record via the portal.

    Stores document metadata. The frontend handles actual file upload to R2.
    No authentication required. The token itself is the credential.
    """
    now = datetime.now(timezone.utc)

    result = await db.execute(
        select(PortalToken).where(
            PortalToken.token == token,
            PortalToken.token_type == "lender",
            PortalToken.expires_at > now,
        )
    )
    portal_token = result.scalar_one_or_none()
    if portal_token is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Lender portal link is invalid or has expired.",
        )

    doc = Document(
        transaction_id=portal_token.transaction_id,
        name=body.name,
        phase=5,  # Financing phase
        responsible_party_role="lender",
    )
    db.add(doc)
    await db.flush()
    await db.refresh(doc)

    return {
        "id": doc.id,
        "transaction_id": doc.transaction_id,
        "name": doc.name,
        "status": doc.status,
        "created_at": doc.created_at.isoformat(),
    }
