"""Stable name normalization for document and deadline matching.

All document checklist names and deadline names are generated by deterministic
Python functions (generate_checklist, generate_timeline). However, if those
strings ever drift between code versions — or if a name was stored with slightly
different casing, punctuation, or whitespace — a naive string comparison will
fail to match what is effectively the same logical item.

normalize_name() collapses all such variation into a single canonical form.
It is the ONLY place where this logic lives.  Apply it on both sides of any
name comparison and on every insert so the canonical_key column stays current.

Examples
--------
"Homeowner's Insurance Binder"         → "homeowners insurance binder"
"Homeowner\u2019s Insurance Binder"    → "homeowners insurance binder"  (curly apostrophe)
"home inspection report"               → "home inspection report"
"Home Inspection Report"               → "home inspection report"
"Inspection_Report"                    → "inspection report"
"WDO (Wood-Destroying Organism)"       → "wdo wood destroying organism"
"Loan Commitment Letter / Clear to Close" → "loan commitment letter clear to close"
"  Extra   Spaces  "                   → "extra spaces"
"""

import re
import unicodedata


def normalize_name(name: str) -> str:
    """Return a stable, lowercase, punctuation-free key for a document or deadline name.

    Transformation pipeline:
      1. NFKD unicode normalization — decomposes ligatures, normalizes curly quotes,
         smart apostrophes, and other look-alike characters to their ASCII base.
      2. Encode to ASCII (ignore) — drops any remaining non-ASCII characters so the
         key is always plain ASCII and safe to store in any varchar column.
      3. Lowercase — makes matching case-insensitive.
      4. Replace any run of non-alphanumeric characters with a single space —
         handles underscores, hyphens, slashes, parentheses, apostrophes, etc.
      5. Strip and collapse internal whitespace — removes leading/trailing spaces
         and collapses multiple internal spaces to one.

    The result is a string containing only lowercase ASCII letters, digits, and
    single spaces — no punctuation, no special characters.

    Args:
        name: Raw display name from the checklist or timeline generator.

    Returns:
        Normalized string suitable for stable equality comparison.
    """
    # Step 1: NFKD decomposition (curly apostrophes, smart quotes → base chars)
    normalized = unicodedata.normalize("NFKD", name)
    # Step 2: drop non-ASCII bytes entirely
    ascii_only = normalized.encode("ascii", errors="ignore").decode("ascii")
    # Step 3: lowercase
    lowered = ascii_only.lower()
    # Step 4: replace any sequence of non-alphanumeric chars with a single space
    spaced = re.sub(r"[^a-z0-9]+", " ", lowered)
    # Step 5: strip and collapse
    return spaced.strip()
